version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: pns_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pns_network
    command: ["--replSet", "rs0", "--bind_ip_all"]

  redis:
    image: redis:alpine
    container_name: pns_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pns_network

  mongo-express:
    image: mongo-express
    container_name: pns_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
    networks:
      - pns_network

volumes:
  mongo_data:
  redis_data:

networks:
  pns_network:
    driver: bridge
